### ISSUE TITLE
ActiveRecord::InvalidForeignKey in spina/admin/images#destroy

### ISSUE THREAD

**Issue by jmalcic** [ulab-committee/ulab-website#568]
## Error in ULAB Website

**ActiveRecord::InvalidForeignKey** in **spina/admin/images#destroy**
PG::ForeignKeyViolation: ERROR:  update or delete on table "spina_conferences_rooms" violates foreign key constraint "fk_rails_f1eb8618f1" on table "spina_conferences_sessions"
DETAIL:  Key (id)=(43) is still referenced from table "spina_conferences_sessions".

[View on Bugsnag](https://app.bugsnag.com/ulab/ulab-website/errors/5fbd6cdea16d1d0017dd289b?event_id=5fbd6cde0064fa44b2770000&i=gh&m=ci)

## Stacktrace

    vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/postgresql_adapter.rb:675 - exec_params

[View full stacktrace](https://app.bugsnag.com/ulab/ulab-website/errors/5fbd6cdea16d1d0017dd289b?event_id=5fbd6cde0064fa44b2770000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by louis-vs** [comment]
In other parts of Spina this kind of issue is handled silently.
