### ISSUE TITLE
ActionView::Template::Error in spina/conferences/primer_theme/journal/issues#index

### ISSUE THREAD

**Issue by jmalcic** [ulab-committee/ulab-website#768]
## Error in ULAB Website

**ActionView::Template::Error** in **spina/conferences/primer_theme/journal/issues#index**
undefined method `has_content?' for nil:NilClass

[View on Bugsnag](https://app.bugsnag.com/ulab/ulab-website/errors/60ae6200e3bea40007fafc78?event_id=60ae6200007ca2ea50840000&i=gh&m=ci)

## Stacktrace

    vendor/bundle/ruby/2.7.0/gems/spina-conferences-primer_theme-0.5.1/app/views/spina/conferences/primer_theme/journal/issues/index.html.haml:20 - block (2 levels) in _vendor_bundle_ruby_______gems_spina_conferences_primer_theme_______app_views_spina_conferences_primer_theme_journal_issues_index_html_haml__347074529824804243_48980

[View full stacktrace](https://app.bugsnag.com/ulab/ulab-website/errors/60ae6200e3bea40007fafc78?event_id=60ae6200007ca2ea50840000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by louis-vs** [comment]
Fixed in `spina-conferences-primer_theme-0.5.2`
