### ISSUE TITLE
RuntimeError in bin/bundle:107

### ISSUE THREAD

**Issue by jmalcic** [ulab-committee/ulab-website#831]
## Error in ULAB Website

**RuntimeError** in **bin/bundle:107**
Try again

[View on Bugsnag](https://app.bugsnag.com/ulab/ulab-website/errors/6132a4ef8e6a310007151b21?event_id=6132a4ef007f97e35ffd0000&i=gh&m=ci)

## Stacktrace

    bin/bundle:107 - load
    bin/bundle:107 - <main>

[View full stacktrace](https://app.bugsnag.com/ulab/ulab-website/errors/6132a4ef8e6a310007151b21?event_id=6132a4ef007f97e35ffd0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by louis-vs** [comment]
bug with production configuration, fixed
