### ISSUE TITLE
StandardError in db:migrate

### ISSUE THREAD

**Issue by jmalcic** [ulab-committee/ulab-website#840]
## Error in ULAB Website

**StandardError** in **db:migrate**
An error has occurred, this and all later migrations canceled:

undefined method `partable' for #<Spina::LayoutPart:0x000055a2dbcc0c08>

[View on Bugsnag](https://app.bugsnag.com/ulab/ulab-website/errors/6137cbd50c5b3600078203c8?event_id=6137cbd5007f8df75e570000&i=gh&m=ci)

## Stacktrace

    db/migrate/20210907202529_change_current_conference_alert_to_text.spina_conferences_primer_theme_engine.rb:7 - block in up
    db/migrate/20210907202529_change_current_conference_alert_to_text.spina_conferences_primer_theme_engine.rb:6 - up
    bin/rake:16 - <main>

[View full stacktrace](https://app.bugsnag.com/ulab/ulab-website/errors/6137cbd50c5b3600078203c8?event_id=6137cbd5007f8df75e570000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by louis-vs** [comment]
This was a bug on Heroku, which is no longer relevant.

**Comment by jmalcic** [comment]
An error linked to this issue has been reopened in Bugsnag
[**StandardError** in **db:migrate**](https://app.bugsnag.com/ulab/ulab-website/errors/6137cbd50c5b3600078203c8?event_id=61390b3a00809b20dee20000&i=gh&m=ra)

**Comment by jmalcic** [comment]
An error linked to this issue has been reopened in Bugsnag
[**StandardError** in **db:migrate**](https://app.bugsnag.com/ulab/ulab-website/errors/6137cbd50c5b3600078203c8?event_id=615da6850083b954b2350000&i=gh&m=ra)
