### ISSUE TITLE
Rack::Timeout::RequestTimeoutException in spina/admin/media_picker#show

### ISSUE THREAD

**Issue by jmalcic** [ulab-committee/ulab-website#873]
## Error in ULAB Website

**Rack::Timeout::RequestTimeoutException** in **spina/admin/media_picker#show**
Request ran for longer than 15000ms 

[View on Bugsnag](https://app.bugsnag.com/ulab/ulab-website/errors/617da4a4be52fc00078a924e?event_id=617da4a400895f63c3f90000&i=gh&m=ci)

## Stacktrace

    gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:687 - exec_prepared

[View full stacktrace](https://app.bugsnag.com/ulab/ulab-website/errors/617da4a4be52fc00078a924e?event_id=617da4a400895f63c3f90000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by louis-vs** [comment]
Hopefully a one-off.
