### ISSUE TITLE
ActionController::BadRequest in GET /%C0%2E%C0%2E\%C0%2E%C0%2E\%C0%2E%C0%2E\boot.ini

### ISSUE THREAD

**Issue by jmalcic** [ulab-committee/ulab-website#876]
## Error in ULAB Website

**ActionController::BadRequest** in **GET /%C0%2E%C0%2E\%C0%2E%C0%2E\%C0%2E%C0%2E\boot.ini**
Invalid path parameters: Invalid encoding for parameter: �.�.\�.�.\�.�.\boot

[View on Bugsnag](https://app.bugsnag.com/ulab/ulab-website/errors/6185d460b5b57100092ce109?event_id=6185d460008955417d7c0000&i=gh&m=ci)

## Stacktrace

    gems/actionpack-6.1.4.1/lib/action_dispatch/request/utils.rb:39 - check_param_encoding

[View full stacktrace](https://app.bugsnag.com/ulab/ulab-website/errors/6185d460b5b57100092ce109?event_id=6185d460008955417d7c0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by louis-vs** [comment]
insulted that they think we're running this on windows; these kinds of errors really shouldn't be logged though
