### ISSUE TITLE
I18n::InvalidLocale in spina/pages#show

### ISSUE THREAD

**Issue by jmalcic** [ulab-committee/ulab-website#877]
## Error in ULAB Website

**I18n::InvalidLocale** in **spina/pages#show**
"..\\..\\..\\..\\..\\..\\..\\..\\ColdFusion8\\lib\\password.properties\\u0000en" is not a valid locale

[View on Bugsnag](https://app.bugsnag.com/ulab/ulab-website/errors/6185d46294f7380007b55c3b?event_id=6185d4620089692402540000&i=gh&m=ci)

## Stacktrace

    gems/i18n-1.8.10/lib/i18n.rb:343 - enforce_available_locales!

[View full stacktrace](https://app.bugsnag.com/ulab/ulab-website/errors/6185d46294f7380007b55c3b?event_id=6185d4620089692402540000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by louis-vs** [comment]
Someone trying to hack, fun.
