### ISSUE TITLE
ActionController::UnknownHttpMethod in PURGE /

### ISSUE THREAD

**Issue by jmalcic** [ulab-committee/ulab-website#878]
## Error in ULAB Website

**ActionController::UnknownHttpMethod** in **PURGE /**
PURGE, accepted HTTP methods are OPTIONS, GET, HEAD, POST, PUT, DELETE, TRACE, CONNECT, PROPFIND, PROPPATCH, MKCOL, COPY, MOVE, LOCK, UNLOCK, VERSION-CONTROL, REPORT, CHECKOUT, CHECKIN, UNCHECKOUT, MKWORKSPACE, UPDATE, LABEL, MERGE, BASELINE-CONTROL, MKACTIVITY, ORDERPATCH, ACL, SEARCH, MKCALENDAR, and PATCH

[View on Bugsnag](https://app.bugsnag.com/ulab/ulab-website/errors/6185d4f8ecc220000802ccb3?event_id=6185d4f8008978de6c7d0000&i=gh&m=ci)

## Stacktrace

    gems/actionpack-6.1.4.1/lib/action_dispatch/http/request.rb:447 - check_method

[View full stacktrace](https://app.bugsnag.com/ulab/ulab-website/errors/6185d4f8ecc220000802ccb3?event_id=6185d4f8008978de6c7d0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by louis-vs** [comment]
script kiddies _real_ desperate with this one
