### ISSUE TITLE
ActiveRecord::StatementInvalid in spina/conferences/primer_theme/blog/posts#index

### ISSUE THREAD

**Issue by jmalcic** [ulab-committee/ulab-website#890]
## Error in ULAB Website

**ActiveRecord::StatementInvalid** in **spina/conferences/primer_theme/blog/posts#index**
PG::UndefinedTable: ERROR:  relation "spina_blog_posts" does not exist
LINE 8:  WHERE a.attrelid = '"spina_blog_posts"'::regclass
                            ^

[View on Bugsnag](https://app.bugsnag.com/ulab/ulab-website/errors/6189207c7ac9a80008043bf2?event_id=6189207c00897833ef690000&i=gh&m=ci)

## Stacktrace

    gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:19 - exec

[View full stacktrace](https://app.bugsnag.com/ulab/ulab-website/errors/6189207c7ac9a80008043bf2?event_id=6189207c00897833ef690000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by louis-vs** [comment]
forgot to run migration, this was fixed almost immediately
