### ISSUE TITLE
ActionController::UnknownFormat in spina/conferences/primer_theme/journal/articles#show

### ISSUE THREAD

**Issue by jmalcic** [ulab-committee/ulab-website#906]
## Error in ULAB Website

**ActionController::UnknownFormat** in **spina/conferences/primer_theme/journal/articles#show**
ActionController::UnknownFormat

[View on Bugsnag](https://app.bugsnag.com/ulab/ulab-website/errors/61af02f6978e100007c1347a?event_id=61af02f6008a3e6bb6aa0000&i=gh&m=ci)

## Stacktrace

    gems/actionpack-6.1.4.1/lib/action_controller/metal/mime_responds.rb:216 - respond_to

[View full stacktrace](https://app.bugsnag.com/ulab/ulab-website/errors/61af02f6978e100007c1347a?event_id=61af02f6008a3e6bb6aa0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by louis-vs** [comment]
Can't reproduce this.
